---
title: 木木么么
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 木木么么,mumumeme,mumu.meme,熊の猫,熊的猫,一个博客树洞。本博客基于Jekyll进行书写。源自生活的点点滴滴和碎碎念。
baseurl: ''
url: https://mumu.meme
author:
  name: 熊的猫
  url: https://mumu.meme/about/
  email: mumumeme@yeah.net
markdown: kramdown
include:
- _pages
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
permalink: "/post/:year:month:day.html"
paginate: 5
exclude:
- Gemfile
- Gemfile.lock
- muji.gemspec
