---
title: 博客沙龙
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 博客沙龙,blog salon,blog.salon,刘看山,一个博客树洞。本博客基于Jekyll进行书写。源自生活的点点滴滴和碎碎念。
baseurl: ''
url: https://blog.salon
author:
  name: 刘看山
  url: https://blog.salon/about/
  email: woaiblog@126.com
markdown: kramdown
include:
- _pages
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
permalink: "/post/:year:month:day.html"
paginate: 5
exclude:
- Gemfile
- Gemfile.lock
- muji.gemspec
